export const RESTAURANT_SUCCESS = 'RESTAURANT_SUCCESS';
export const RESTAURANT_REQUEST = 'RESTAURANT_REQUEST';
export const RESTAURANT_FAIL = 'RESTAURANT_FAIL';
export const INPUT_FAIL = 'INPUT_FAIL';
